name: rea_estate_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Dart SDK 3.x

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4 # Latest null-safe version
  cloud_firestore: ^4.6.0   # Latest null-safe version
  http: ^1.1.0              # Null-safe version
  cupertino_icons: ^1.0.8   # Latest null-safe version
  image_picker: ^0.8.7      # Latest null-safe version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0      # Ensure latest lints are used

flutter:
  uses-material-design: true
  assets:
    - assets/images/
